mvp: added retry attempts for specific k8s setup steps
Signed-off-by: Abhishek Kumar <abhishek.mrt22@gmail.com>

diff --git a/conf/k8s-master.yml b/conf/k8s-master.yml
--- a/conf/k8s-master.yml
+++ b/conf/k8s-master.yml
@@ -124,8 +124,33 @@ write-files:
       systemctl enable kubelet && systemctl start kubelet
       modprobe br_netfilter && sysctl net.bridge.bridge-nf-call-iptables=1
 
-      kubeadm config images pull
-      kubeadm init --pod-network-cidr=10.244.0.0/16 --token {{ k8s_master.cluster.token }} {{ k8s_master.cluster.ip }}
+      MAX_SETUP_CRUCIAL_CMD_ATTEMPTS=3
+      crucial_cmd_attempts=1
+      while true; do
+        if (( "$crucial_cmd_attempts" > "$MAX_SETUP_CRUCIAL_CMD_ATTEMPTS" )); then
+          echo "Error: kubeadm pull images failed!"
+          break
+        fi
+        set +e
+        kubeadm config images pull
+        set -e
+        if [ $? -eq 0 ]; then
+          break;
+        fi
+      done
+      crucial_cmd_attempts=1
+      while true; do
+        if (( "$crucial_cmd_attempts" > "$MAX_SETUP_CRUCIAL_CMD_ATTEMPTS" )); then
+          echo "Error: kubeadm init failed!"
+          break
+        fi
+        set +e
+        kubeadm init --pod-network-cidr=10.244.0.0/16 --token {{ k8s_master.cluster.token }} {{ k8s_master.cluster.ip }}
+        set -e
+        if [ $? -eq 0 ]; then
+          break;
+        fi
+      done
 
   - path: /opt/bin/deploy-kube-system
     permissions: 0700
diff --git a/conf/k8s-node.yml b/conf/k8s-node.yml
--- a/conf/k8s-node.yml
+++ b/conf/k8s-node.yml
@@ -100,8 +100,21 @@ write-files:
 
       systemctl enable kubelet && systemctl start kubelet
       modprobe br_netfilter && sysctl net.bridge.bridge-nf-call-iptables=1
-      
-      kubeadm config images pull
+
+      MAX_SETUP_CRUCIAL_CMD_ATTEMPTS=3
+      crucial_cmd_attempts=1
+      while true; do
+        if (( "$crucial_cmd_attempts" > "$MAX_SETUP_CRUCIAL_CMD_ATTEMPTS" )); then
+          echo "Error: kubeadm pull images failed!"
+          break
+        fi
+        set +e
+        kubeadm config images pull
+        set -e
+        if [ $? -eq 0 ]; then
+          break;
+        fi
+      done
 
   - path: /opt/bin/deploy-kube-system
     permissions: 0700
