ccs: mvp changes for next release (#65)
This implements the following new functionalities and optimizations,

Offline installation of k8s binaries and docker images.
To deploy cluster faster and more reliably, changes have been made to allow installation of k8s binaries(kubeadm, kubectl, etc.) required docker images through an ISO. An ISO with binaries can be prepared and registered with ACS. To make plugin aware about the ISO, name of ISO can be set in the globa setting cloud.container.cluster.binaries.iso.name. The plugin will first attempt to install binaries and images from ISO and if not found, it will continue with the online installation. This brings down cluster deployment time to nearly 5mins.

kube-config based access
To provide more secure and reliable access to k8s cluster remotely, changes have been made to download and access Kubernetes admin.conf file for the cluster. With the help of kubectl tool and this conf file, user can connect to the cluster. getContainerClusterConfig API has been added for this.

Optimizations in accessing cluster states
Code changes have been done to check running states of the cluster. Rather than using kubectl on MS to find running addon service on cluster, the plugin will make the call with k8s master itself.

SSH access
Changes for exporting management server's SSH key to all cluster VMs.
Port forwarding rule for all the cluster VMs have been added to allow SSH access (Starting with port 2222 for master and subsequent ports for node VMs)

Unique cluster token
Changes for using a unique token for each cluster. K8s cluster needs a toke with format <6 chars>.<16 chars>, which allows new node VMs to join the cluster. CCS Cluster's DB UUID has been used for this purpose.

Signed-off-by: Abhishek Kumar <abhishek.mrt22@gmail.com>

diff --git a/conf/k8s-node.yml b/conf/k8s-node.yml
--- a/conf/k8s-node.yml
+++ b/conf/k8s-node.yml
@@ -7,28 +7,100 @@ write-files:
     owner: root:root
     content: |
       #!/bin/bash -e
+      
       export PATH=$PATH:/opt/bin
 
-      CNI_VERSION="v0.7.1"
-      mkdir -p /opt/cni/bin
-      curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz" | tar -C /opt/cni/bin -xz
-
-      CRICTL_VERSION="v1.11.1"
-      mkdir -p /opt/bin
-      curl -L "https://github.com/kubernetes-incubator/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C /opt/bin -xz
-
       RELEASE="v1.11.4"
-      mkdir -p /opt/bin
-      cd /opt/bin
-      curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
-      chmod +x {kubeadm,kubelet,kubectl}
+      ISO_MOUNT_DIR=/mnt/k8sdisk
+      BINARIES_DIR=${ISO_MOUNT_DIR}/${RELEASE}
+      CNI_VERSION="v0.7.1"
+      CRICTL_VERSION="v1.11.1"
+      ATTEMPT_OFFLINE_INSTALL=true
+      setup_complete=false
 
-      curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
-      mkdir -p /etc/systemd/system/kubelet.service.d
-      curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/10-kubeadm.conf" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
+      OFFLINE_INSTALL_ATTEMPT_SLEEP=5
+      MAX_OFFLINE_INSTALL_ATTEMPTS=36
+      offline_attempts=1
+      while true; do
+        if (( "$offline_attempts" > "$MAX_OFFLINE_INSTALL_ATTEMPTS" )); then
+          echo "Warning: Offline install timed out!"
+          break
+        fi
+        set +e
+        output=`blkid -o device -t TYPE=iso9660`
+        set -e
+        if [ "$output" != "" ]; then
+          while read -r line; do
+            mkdir "${ISO_MOUNT_DIR}"
+            set +e
+            mount -o ro "${line}" "${ISO_MOUNT_DIR}"
+            set -e
+            if [ $? -eq 0 ]; then
+              if [ -d "$BINARIES_DIR" ]; then
+                break
+              else
+                umount "${line}" && rmdir "${ISO_MOUNT_DIR}"
+              fi
+            fi
+          done <<< "$output"
+        fi
+        if [ -d "$BINARIES_DIR" ]; then
+          break
+        fi
+        echo "Waiting for Binaries directory $BINARIES_DIR to be available, sleeping for $OFFLINE_INSTALL_ATTEMPT_SLEEP seconds, attempt: $offline_attempts"
+        sleep $OFFLINE_INSTALL_ATTEMPT_SLEEP
+        offline_attempts=$[$offline_attempts + 1]
+      done
+
+      if [ -d "$BINARIES_DIR" ]; then
+        ### Binaries available offline ###
+        echo "Installing binaries from ${BINARIES_DIR}"
+        mkdir -p /opt/cni/bin
+        tar -f "${BINARIES_DIR}/cni/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz" -C /opt/cni/bin -xz
+
+        mkdir -p /opt/bin
+        tar -f "${BINARIES_DIR}/cri-tools/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" -C /opt/bin -xz
+
+        mkdir -p /opt/bin
+        cd /opt/bin
+        cp -a ${BINARIES_DIR}/k8s/{kubeadm,kubelet,kubectl} /opt/bin
+        chmod +x {kubeadm,kubelet,kubectl}
+
+        sed "s:/usr/bin:/opt/bin:g" ${BINARIES_DIR}/kubelet.service > /etc/systemd/system/kubelet.service
+        mkdir -p /etc/systemd/system/kubelet.service.d
+        sed "s:/usr/bin:/opt/bin:g" ${BINARIES_DIR}/10-kubeadm.conf > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
+
+        output=`ls ${BINARIES_DIR}/docker/`
+        if [ "$output" != "" ]; then
+          while read -r line; do
+            docker load < "${BINARIES_DIR}/docker/$line"
+          done <<< "$output"
+          setup_complete=true
+        fi
+        umount "${ISO_MOUNT_DIR}" && rmdir "${ISO_MOUNT_DIR}"
+      fi
+      if [ "$setup_complete" = false ]; then
+        ###  Binaries not available offline ###
+        echo "Warning: ${BINARIES_DIR} not found. Will get binaries and docker images from Internet."
+        mkdir -p /opt/cni/bin
+        curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz" | tar -C /opt/cni/bin -xz
+
+        mkdir -p /opt/bin
+        curl -L "https://github.com/kubernetes-incubator/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C /opt/bin -xz
+
+        mkdir -p /opt/bin
+        cd /opt/bin
+        curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
+        chmod +x {kubeadm,kubelet,kubectl}
+
+        curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
+        mkdir -p /etc/systemd/system/kubelet.service.d
+        curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/10-kubeadm.conf" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
+      fi
+
       systemctl enable kubelet && systemctl start kubelet
-      sysctl net.bridge.bridge-nf-call-iptables=1
-
+      modprobe br_netfilter && sysctl net.bridge.bridge-nf-call-iptables=1
+      
       kubeadm config images pull
 
   - path: /opt/bin/deploy-kube-system
@@ -41,7 +113,7 @@ write-files:
       modprobe ip_vs_sh
       modprobe nf_conntrack_ipv4
       export PATH=$PATH:/opt/bin
-      kubeadm join {{ k8s_master.default_ip }}:6443 --token a4qgg6.84hjisyqzvth7yp6 --discovery-token-unsafe-skip-ca-verification
+      kubeadm join {{ k8s_master.default_ip }}:6443 --token {{ k8s_master.cluster.ip }} --discovery-token-unsafe-skip-ca-verification
 
 coreos:
   units:
