conf: allow docker image load failure while setup
Signed-off-by: Abhishek Kumar <abhishek.mrt22@gmail.com>

diff --git a/conf/k8s-master.yml b/conf/k8s-master.yml
--- a/conf/k8s-master.yml
+++ b/conf/k8s-master.yml
@@ -44,6 +44,8 @@ write-files:
       OFFLINE_INSTALL_ATTEMPT_SLEEP=5
       MAX_OFFLINE_INSTALL_ATTEMPTS=36
       offline_attempts=1
+      MAX_SETUP_CRUCIAL_CMD_ATTEMPTS=3
+      crucial_cmd_attempts=1
       while true; do
         if (( "$offline_attempts" > "$MAX_OFFLINE_INSTALL_ATTEMPTS" )); then
           echo "Warning: Offline install timed out!"
@@ -54,7 +56,7 @@ write-files:
         set -e
         if [ "$output" != "" ]; then
           while read -r line; do
-            if [! -d "${ISO_MOUNT_DIR}" ]; then
+            if [ ! -d "${ISO_MOUNT_DIR}" ]; then
               mkdir "${ISO_MOUNT_DIR}"
             fi
             retval=0
@@ -100,7 +102,22 @@ write-files:
         output=`ls ${BINARIES_DIR}/docker/`
         if [ "$output" != "" ]; then
           while read -r line; do
-            docker load < "${BINARIES_DIR}/docker/$line"
+            crucial_cmd_attempts=1
+            while true; do
+              if (( "$crucial_cmd_attempts" > "$MAX_SETUP_CRUCIAL_CMD_ATTEMPTS" )); then
+                echo "Loading docker image ${BINARIES_DIR}/docker/$line failed!"
+                break;
+              fi
+              retval=0
+              set +e
+              docker load < "${BINARIES_DIR}/docker/$line"
+              retval=$?
+              set -e
+              if [ $retval -eq 0 ]; then
+                break;
+              fi
+              crucial_cmd_attempts=$[$crucial_cmd_attempts + 1]
+            done
           done <<< "$output"
           setup_complete=true
         fi
@@ -128,7 +145,6 @@ write-files:
       systemctl enable kubelet && systemctl start kubelet
       modprobe br_netfilter && sysctl net.bridge.bridge-nf-call-iptables=1
 
-      MAX_SETUP_CRUCIAL_CMD_ATTEMPTS=3
       crucial_cmd_attempts=1
       while true; do
         if (( "$crucial_cmd_attempts" > "$MAX_SETUP_CRUCIAL_CMD_ATTEMPTS" )); then
